CREATE DATABASE gestionRentaMunicipal;

USE gestionRentaMunicipal;

CREATE TABLE `User`(
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(100) NOT NULL,
	`LastName` VARCHAR(100) NOT NULL,
	`Email` VARCHAR(255) NOT NULL UNIQUE,
	`Password` VARCHAR(255) NOT NULL, 
	`Identification` INTEGER NOT NULL UNIQUE,
	`Phone` INTEGER NOT NULL,
	`Address` VARCHAR(150),
	`IsDeleted` BOOLEAN NOT NULL,
	PRIMARY KEY ('Id')
); 

CREATE TABLE `Rol`(
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	`IsDeleted` BOOLEAN NOT NULL,
	PRIMARY KEY ('Id')
);

CREATE TABLE `Permission`(
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	`Description` TEXT NOT NULL,
	`IsDeleted` BOOLEAN NOT NULL,
	PRIMARY KEY ('Id')
);

CREATE TABLE `Form`(
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	`Description` TEXT NOT NULL,
	`IsDeleted` BOOLEAN NOT NULL,
	PRIMARY KEY ('Id')
);

CREATE TABLE `Bill`(
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Barcode` INTEGER NOT NULL UNIQUE,
	`IssueDate` DATETIME NOT NULL,
	`ExpirationDate` DATETIME NOT NULL,
	`Amount` DECIMAL(20,2) NOT NULL,
	`State` ENUM('Vencida','Pagada','Pendiente'),
	PRIMARY KEY ('Id')
);

CREATE TABLE `Module`(
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(100) NOT NULL,
	`Description` TEXT NOT NULL,
	`Code` VARCHAR(10) NOT NULL,
	`IsDeleted` BOOLEAN NOT NULL,
	PRIMARY KEY ('Id')
);

CREATE TABLE `Statement`(
	`Id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Type` VARCHAR(150) NOT NULL,
	`Title` VARCHAR(150) NOT NULL,
	`Description` TEXT NOT NULL,
	`GenerationDate` DATETIME NOT NULL,
	`PeriodStart` DATETIME NOT NULL,
	`PeriodEnd` DATETIME NOT NULL,
	`TotalAmount` DECIMAL(20,2) NOT NULL,
	PRIMARY KAY ('Id')
);
